### ISSUE TITLE
Add progressbar to console output

### ISSUE THREAD

**Issue by ChristianWieck** [flowcean/flowcean#125]
Some operations may take a while to complete (loading data / transforms / ...). We should define a standard way to display the progress to the user.

**Comment by schmidma** [comment]
We probably should just use https://github.com/tqdm/tqdm

**Comment by ChristianWieck** [comment]
Yep, `tqdm` seems to be the go-to solution for this. I would try to implement it for the directory_loader in #110.

**Comment by schmidma** [comment]
I'd suggest to split this into a separate feature, just to ease the review and discussion

**Comment by ChristianWieck** [comment]
Fair. I'll mark #110 as ready and create a new PR for the progress logging.
