### ISSUE TITLE
Update protobuf definition for current implementation state

### ISSUE THREAD

**Issue by ChristianWieck** [flowcean/flowcean#131]
The protobuf definition is severly outdated and should be updated / reworked to reflect the "current state". This includes time series handling and potentially multi-dimensional data.

**Comment by newLabAspect** [comment]
This might be redundant / included in #37 and #16. Should we join them?

**Comment by ChristianWieck** [comment]
I would agree to merge this with #16. I think #37 has a different scope and should remain a separate issue.

**Comment by schmidma** [comment]
Added a description  to #16
