### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by stbalduin** [flowcean/flowcean#32]
- evaluation.py is currently in subfolder metrics maybe there is a better location for this file
- evaluate() function only applicable to OfflineEnvironment object

(Gitlab Issue 116, created by @mknitt)

**Comment by stbalduin** [comment]
_Comment from @schmidma_:

As we now introduced active and incremental/online learning, we may have to rethink the topic of metrics in general.

Currently, metrics are only applicable to offline scenarios. We might want to introduce "evaluation strategies" for different setups.

**Comment by schmidma** [comment]
Superseded by #65
