### ISSUE TITLE
Allow (Path)DataLoader to index files

### ISSUE THREAD

**Issue by stbalduin** [flowcean/flowcean#35]
Right now DataLoader (and PathDataLoader as introduced in [edit: Gitlab Issue 90] in particular) can only load files provided to them. To allow for a more flexible approach it might be an idea to offer a find_files / index method or similar which provides the loader with a path to a folder and allows it to discover all loadable data within it.
Upsides of such an approach:

No need to wory about file extensions. The loader can discover all files it can load (and might use the extension for that), but the user doesn't need to provide one.
Support for more "complicated" data types which do not consist of a single file (e.g. ros bags)

Downsides:

Adds more complexity to the code (there must be an index method, however this could be overloaded / inherited for "simple" loaders)
Only really useful for the time series loader (where this problem originally arose).

@mknitt perhaps you have an opinion on this? This could be a relatively simple solution to your "rosbag problem" as well as the problem of different length data from different sources.

(Gitlab Issue 113, created by @ChristianWieck)

**Comment by ChristianWieck** [comment]
There is a new proposal in #110 for this.
