### ISSUE TITLE
`Verbose` flag not working

### ISSUE THREAD

**Issue by newLabAspect** [flowcean/flowcean#60]
When calling AGenC with the verbose flag, debug log messages are not show in the console.
Steps to reproduce:

Call an example experiment with agenc --verbose --experiment experiment.yaml

Expect debug output from the automatically added select transform

(Gitlab Issue 95, created by @ChristianWieck )

**Comment by ChristianWieck** [comment]
As the CLI is now obsolete and no longer used, the flag is no longer relevant. The log level can be adjusted correctly in the python code itself.
