### ISSUE TITLE
Handling of Time Series Data

### ISSUE THREAD

**Issue by newLabAspect** [flowcean/flowcean#62]
Involves:
- [x] #42 
- [x] #41 
- [x] #40 
- [x] #39 
- [x] #38 
- [x] #34 

(Gitlab Issue 97, created by @newLabAspect)

**Comment by newLabAspect** [comment]
@ChristianWieck _commented:_

Perhaps this could be solved by reintroducing metadata for each column? This would at least solve the problem for the machine learner.

**Comment by newLabAspect** [comment]
@mknitt _commented:_

[@JanChristianWieck](https://github.com/JanChristianWieck) and I discussed this and we think a good solution would be to save the time series in multidimensional numpy arrays inside of polars dataframes.
```

| feature 1           | feature 2               |
| ------------------- | ----------------------- |
| np.array([[0,2,4],  | np.array([[0,1,2,3,4],  |
|           [3,5,4]]) |           [2,7,1,9,6]]) |      
|                     |                         |
| np.array([[0,2],    | np.array([[0,1,2],      |
|           [2,7]])   |           [1,3,2]])     |      
|                     |                         | 
```
Each time series would be structured like this:

`np.array([time, data])`

**Comment by newLabAspect** [comment]
@ChristianWieck _commented:_

As discussed in the software meeting on 29.02. we move from `np.array` to `pl.List` as they are more performand. Only downside is, that only vectors are supported. The link between data and time vector needs to be implemented in a different way (e.g. hard-coded `<feature_name>` ->` t_<feature_name>` or metadata).

**Comment by ChristianWieck** [comment]
As discussed at our meeting on 04.06.:
We want to use `pl.Structs` for storing time series, by storing the time vector in a field `t` and the associated value vector in the field `value`.

**Comment by schmidma** [comment]
All individually mentioned issues for this meta-issue are resolved, closing this for now.
